In [3]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## 1. Getting Started

### 1.1 Tensors

Tensors are similar to NumPy’s ndarrays, 

with the addition being that

Tensors can also be used on a GPU to accelerate computing.



In [4]:
from __future__ import print_function
import torch

1. Construct a 5x3 matrix, uninitialized:



In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[    0.0000,    -0.0000,  2713.6836],
        [   -2.0005,     0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000]])


2. Construct a randomly initialized matrix:



In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.5458,  0.7090,  0.9167],
        [ 0.0338,  0.5544,  0.3385],
        [ 0.4633,  0.0379,  0.6071],
        [ 0.7130,  0.9917,  0.8431],
        [ 0.9524,  0.6951,  0.5240]])


3. Construct a matrix filled zeros and of dtype long:



In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


4. Construct a tensor directly from data:



In [8]:
# just as tf.tensorflow
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


5. or create a tensor basing on existing tensor. 

These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size
# x is changed here

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-1.5078, -0.4029,  0.7471],
        [ 0.8517,  0.6163, -1.3089],
        [ 1.0734,  0.5496, -0.0899],
        [-0.0441, -0.5918,  0.5969],
        [ 0.4424,  0.2601, -0.1620]])


6. Get its size:



In [10]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

### 1.2 Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

1. Addition: syntax 1



In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9724, -0.0658,  1.5020],
        [ 0.8659,  1.3468, -0.9561],
        [ 1.2167,  1.0294,  0.3080],
        [ 0.9475, -0.4492,  1.1056],
        [ 0.5888,  0.5532,  0.8050]])


2. Addition: syntax 2



In [12]:
print(torch.add(x, y))

tensor([[-0.9724, -0.0658,  1.5020],
        [ 0.8659,  1.3468, -0.9561],
        [ 1.2167,  1.0294,  0.3080],
        [ 0.9475, -0.4492,  1.1056],
        [ 0.5888,  0.5532,  0.8050]])


3. Addition: providing an output tensor as argument



In [13]:
result = torch.empty(5, 3) # uninitialized
torch.add(x, y, out=result)
print(result)

tensor([[-0.9724, -0.0658,  1.5020],
        [ 0.8659,  1.3468, -0.9561],
        [ 1.2167,  1.0294,  0.3080],
        [ 0.9475, -0.4492,  1.1056],
        [ 0.5888,  0.5532,  0.8050]])


4. Addition: in-place



In [14]:
print(y)

# adds x to y
y.add_(x)
print(y)

# this will change y itself

tensor([[ 0.5354,  0.3371,  0.7549],
        [ 0.0143,  0.7306,  0.3528],
        [ 0.1433,  0.4798,  0.3978],
        [ 0.9916,  0.1425,  0.5087],
        [ 0.1464,  0.2931,  0.9670]])
tensor([[-0.9724, -0.0658,  1.5020],
        [ 0.8659,  1.3468, -0.9561],
        [ 1.2167,  1.0294,  0.3080],
        [ 0.9475, -0.4492,  1.1056],
        [ 0.5888,  0.5532,  0.8050]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

5. You can use standard NumPy-like indexing with all bells and whistles!



In [15]:
x

tensor([[-1.5078, -0.4029,  0.7471],
        [ 0.8517,  0.6163, -1.3089],
        [ 1.0734,  0.5496, -0.0899],
        [-0.0441, -0.5918,  0.5969],
        [ 0.4424,  0.2601, -0.1620]])

In [16]:
print(x[:, 1])

tensor([-0.4029,  0.6163,  0.5496, -0.5918,  0.2601])


6. Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
                   # just as numpy
    
print(y)
print(z)
print(x.size(), y.size(), z.size())

tensor([ 0.6180,  0.0153,  0.5402,  1.0859, -1.0026,  1.3804,  0.5412,
        -1.5597, -1.1516, -2.1706,  0.6504,  1.0570, -1.7037,  0.6435,
        -1.6410,  0.9028])
tensor([[ 0.6180,  0.0153,  0.5402,  1.0859, -1.0026,  1.3804,  0.5412,
         -1.5597],
        [-1.1516, -2.1706,  0.6504,  1.0570, -1.7037,  0.6435, -1.6410,
          0.9028]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


7. If you have a one element tensor, use ``.item()`` to get the value as a Python number



In [18]:
x = torch.randn(1)
print(x)
print(x.item())

# x = torch.randn(3, 4)
# print(x)
# print(x.item()) 
# --: this will raise an Error
#     As the x.item() only return scalar for one element tensor

tensor([-0.8821])
-0.8820635676383972


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

## 2. NumPy Bridge


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

### 2.1 Converting a Torch Tensor to a NumPy Array




In [20]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [22]:
a.add_(1) # change a itself, a and b share the same memory
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


### 2.2 Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

### 3. CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.



In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!